### ISSUE TITLE
Топологическая сортировка

### ISSUE THREAD

**Issue by S1x6** [S1x6/TopSort#1]
@avkomar Закончил топсорт, проверьте код. Все тесты прошел

**Comment by avkomar** [comment]
@S1x6 ,
мне все нравится.

Два замечания, которые скорее к структуре и формлению.

1. местами плывет форматирование - используйте автоформатирование в вашей IDE
2. если у вас есть "private" функции которые вы используете в одном модуле только для внутренних функций, то не нужно выносить их в заголовочный файл. Их можно удалить из header-файла и декларацию перенести в начало самого модуля (.c - файла)

**Comment by avkomar** [comment]
Задача принята. можете закрывать это issue.
